[pytest]
addopts = -ra --strict-markers --strict-config --html=reports/report.html --self-contained-html --alluredir=reports/allure-results --reruns 1 --reruns-delay 1
bdd_features_base_dir = tests/features
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: critical business flows
    regression: broad regression tests
    login: login related scenarios
    topup: top-up purchase scenarios
